CREATE TABLE consumed_events (
    event_id UUID PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    partition_id INTEGER NOT NULL,
    topic_offset BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_consumed_events_topic_partition_offset UNIQUE (topic, partition_id, topic_offset)
);

CREATE TABLE member_product_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    member_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    drop_id BIGINT,
    interaction_type VARCHAR(20) NOT NULL
        CHECK (interaction_type IN ('VIEW', 'CART_ADD', 'PURCHASE')),
    quantity INTEGER NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_member_product_interactions_event_id UNIQUE (event_id)
);
CREATE INDEX idx_mpi_member_occurred ON member_product_interactions (member_id, occurred_at DESC);
CREATE INDEX idx_mpi_member_product_type_occurred ON member_product_interactions (member_id, product_id, interaction_type, occurred_at DESC);
CREATE INDEX idx_mpi_product_type_occurred ON member_product_interactions (product_id, interaction_type, occurred_at DESC);
CREATE INDEX idx_mpi_occurred ON member_product_interactions (occurred_at);

CREATE TABLE member_deletion_markers (
    member_id BIGINT PRIMARY KEY,
    latest_event_id UUID NOT NULL,
    withdrawn_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_member_deletion_markers_latest_event_id UNIQUE (latest_event_id)
);

CREATE TABLE product_embedding_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    latest_event_id UUID NOT NULL,
    event_type VARCHAR(20) NOT NULL
        CHECK (event_type IN ('CREATED', 'UPDATED', 'DELETED')),
    name VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    product_type VARCHAR(20),
    source_hash VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    last_error_code VARCHAR(100),
    source_occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_embedding_tasks_product_id UNIQUE (product_id),
    CONSTRAINT uq_product_embedding_tasks_latest_event_id UNIQUE (latest_event_id)
);
CREATE INDEX idx_pet_status_next_attempt ON product_embedding_tasks (status, next_attempt_at);

CREATE TABLE product_embedding_metadata (
    product_id BIGINT PRIMARY KEY,
    source_hash VARCHAR(100) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    dimensions INTEGER NOT NULL,
    index_version VARCHAR(20) NOT NULL,
    source_occurred_at TIMESTAMPTZ NOT NULL,
    embedded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);