apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ai-service-to-ai-postgres
  namespace: openbake
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ai-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres-backup
      ports:
        - protocol: TCP
          port: 5432
