services:
  backend:
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      AUTH_MODE: jwt

  member-service:
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      AUTH_MODE: jwt

  payment-service:
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      AUTH_MODE: jwt