apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
data:
  prometheus.yml: |
    apiVersion: 1

    prune: true

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
data:
  openbake.yml: |
    apiVersion: 1

    providers:
      - name: OpenBake
        orgId: 1
        folder: OpenBake
        type: file
        disableDeletion: false
        editable: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
