apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 1Gi
