services:
  prometheus:
    image: prom/prometheus
    container_name: openbake-prometheus

    ports:
      - "9090:9090"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=3d"
      - "--storage.tsdb.retention.size=1GB"
      - "--web.enable-remote-write-receiver"

    mem_limit: 512m

volumes:
  prometheus-data: