apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: openbake
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
data:
  DB_URL: "jdbc:postgresql://core-postgres:5432/openbake"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MEMBER_SERVICE_URL: "http://member-service:8081"
  PAYMENT_SERVICE_URL: "http://payment-service:8082"
  AI_SERVICE_URL: "http://ai-service:8083"
  ELASTICSEARCH_URIS: "http://elasticsearch:9200"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  GOOGLE_CLIENT_ID: "339573275035-sc73apjmoto67cmvrn6usrqqtmm6d2aa.apps.googleusercontent.com"
  SPRING_PROFILES_ACTIVE: "prod"
