apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: openbake
  labels:
    app.kubernetes.io/name: member-service
    app.kubernetes.io/component: member
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
data:
  MEMBER_DB_URL: "jdbc:postgresql://member-postgres:5432/openbake_member"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  GOOGLE_CLIENT_ID: "339573275035-sc73apjmoto67cmvrn6usrqqtmm6d2aa.apps.googleusercontent.com"
  SPRING_PROFILES_ACTIVE: "prod"
