apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: openbake
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: payment
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
data:
  PAYMENT_DB_URL: "jdbc:postgresql://payment-postgres:5432/openbake_payment"
  SPRING_PROFILES_ACTIVE: "prod"
