apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: openbake
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: payment
    app.kubernetes.io/part-of: openbake
    app.kubernetes.io/instance: production
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
