#!/usr/bin/env bash
# ============================================================================
# payment 데이터를 기존 공유 DB(openbake)에서 payment-postgres(openbake_payment)로 이전한다.
#
# 사전 조건:
#   - docker compose로 postgres, payment-postgres 둘 다 접근 가능해야 한다
#     (payment-postgres는 호스트 포트가 안 열려있어서 docker compose exec로만 접근)
#   - 소스(openbake) DB는 로컬 5432 포트로 접근 가능해야 한다(docker-compose.yaml 기본값)
#
# 사용법:
#   ./scripts/migrations/payment-service-data-migration/migrate.sh
#
# 이미 이전된 상태에서 다시 실행하면 목적지에 데이터가 있다는 걸 감지하고
# 안전하게 중단한다(중복 삽입 방지). 강제로 다시 하고 싶으면 --force.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SOURCE_HOST="${SOURCE_HOST:-localhost}"
SOURCE_PORT="${SOURCE_PORT:-5432}"
SOURCE_DB="${SOURCE_DB:-openbake}"
SOURCE_USER="${SOURCE_USER:-openbake}"
SOURCE_PASSWORD="${SOURCE_PASSWORD:-openbake}"

DEST_SERVICE="${DEST_SERVICE:-payment-postgres}"   # docker-compose 서비스명
DEST_DB="${DEST_DB:-openbake_payment}"
DEST_USER="${DEST_USER:-openbake}"

TABLES=(deposit_accounts wallet_transactions charge_requests order_payments payment_records)

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

log() { echo "[migrate] $*"; }
psql_source() { PGPASSWORD="$SOURCE_PASSWORD" psql -h "$SOURCE_HOST" -p "$SOURCE_PORT" -U "$SOURCE_USER" -d "$SOURCE_DB" -v ON_ERROR_STOP=1 "$@"; }
psql_dest() { docker compose exec -T "$DEST_SERVICE" psql -U "$DEST_USER" -d "$DEST_DB" -v ON_ERROR_STOP=1 "$@"; }

log "1/6 payment-postgres 컨테이너 기동 확인"
docker compose up -d "$DEST_SERVICE"
for _ in $(seq 1 30); do
  if docker compose exec -T "$DEST_SERVICE" pg_isready -U "$DEST_USER" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
if ! docker compose exec -T "$DEST_SERVICE" pg_isready -U "$DEST_USER" >/dev/null 2>&1; then
  echo "[migrate] ERROR: $DEST_SERVICE 가 30초 안에 준비되지 않았습니다." >&2
  exit 1
fi

log "2/6 목적지 데이터 존재 여부 확인"
existing=$(psql_dest -tAc "SELECT count(*) FROM deposit_accounts;" 2>/dev/null || echo "0")
if [[ "$existing" != "0" && "$FORCE" -ne 1 ]]; then
  echo "[migrate] ERROR: openbake_payment.deposit_accounts 에 이미 데이터(${existing}건)가 있습니다." >&2
  echo "[migrate]        중복 삽입을 막기 위해 중단합니다. 다시 하려면 --force 로 실행하세요" >&2
  echo "[migrate]        (--force 는 스키마만 재적용할 뿐 기존 행을 지우지 않으니, 정말 새로 하려면 직접 TRUNCATE 먼저 하세요)." >&2
  exit 1
fi

log "3/6 목적지에 스키마 적용 (이미 있으면 건너뜀 - IF NOT EXISTS)"
cat "$SCRIPT_DIR/schema.sql" | psql_dest

log "4/6 소스에서 데이터만 덤프해서 목적지로 복사"
# wallet_transactions가 deposit_accounts에 FK 의존이 있으므로
# --disable-triggers로 FK 검사를 일시 비활성화하고 전체를 한 번에 복사한다.
# pg_dump 테이블 순서: deposit_accounts → wallet_transactions → 나머지 (FK 순서)
TABLE_ARGS=""
for t in "${TABLES[@]}"; do
  TABLE_ARGS="$TABLE_ARGS -t $t"
done
PGPASSWORD="$SOURCE_PASSWORD" pg_dump -h "$SOURCE_HOST" -p "$SOURCE_PORT" -U "$SOURCE_USER" -d "$SOURCE_DB" \
  --data-only --disable-triggers $TABLE_ARGS \
  | psql_dest

log "5/6 시퀀스 재조정 (IDENTITY 컬럼)"
# 모든 테이블이 BIGINT GENERATED BY DEFAULT AS IDENTITY를 사용한다.
# PostgreSQL에서 identity 시퀀스 이름은 {table}_{column}_seq 패턴이다.
psql_dest -c "
SELECT setval(pg_get_serial_sequence('deposit_accounts', 'id'), COALESCE((SELECT MAX(id) FROM deposit_accounts), 1));
SELECT setval(pg_get_serial_sequence('wallet_transactions', 'id'), COALESCE((SELECT MAX(id) FROM wallet_transactions), 1));
SELECT setval(pg_get_serial_sequence('charge_requests', 'id'), COALESCE((SELECT MAX(id) FROM charge_requests), 1));
SELECT setval(pg_get_serial_sequence('order_payments', 'id'), COALESCE((SELECT MAX(id) FROM order_payments), 1));
SELECT setval(pg_get_serial_sequence('payment_records', 'id'), COALESCE((SELECT MAX(id) FROM payment_records), 1));
"

log "6/6 검증 - 소스/목적지 행 개수 비교"
all_match=true
for t in "${TABLES[@]}"; do
  src_count=$(psql_source -tAc "SELECT count(*) FROM $t;" 2>/dev/null || echo "0")
  dst_count=$(psql_dest -tAc "SELECT count(*) FROM $t;")
  echo "$t: source=$src_count dest=$dst_count"
  if [[ "$src_count" != "$dst_count" ]]; then
    all_match=false
  fi
done

if [[ "$all_match" != "true" ]]; then
  echo "[migrate] ERROR: 행 개수가 일치하지 않습니다. 위 로그를 확인하세요." >&2
  exit 1
fi

log "완료. payment-service의 DB_URL을 payment-postgres로 돌린 뒤 재기동해서 결제/충전 등 실제 동작을 확인하세요."
log "기존 공유 DB(openbake)의 payment 테이블들은 문제없이 며칠 운영해본 뒤 정리를 권장합니다(바로 지우지 마세요)."
