-- payment-postgres(openbake_payment DB)에 적용할 스키마.
-- payment-service 엔티티 구조를 그대로 옮긴 것이다.
-- Hibernate ddl-auto: update로 생성되는 것과 동일한 구조.

-- 1. deposit_accounts
CREATE TABLE IF NOT EXISTS deposit_accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type VARCHAR(255) NOT NULL,
    member_id    BIGINT UNIQUE,
    balance      NUMERIC,
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT deposit_accounts_account_type_check CHECK (account_type IN ('MEMBER', 'PLATFORM'))
);

-- 2. wallet_transactions
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deposit_account_id BIGINT NOT NULL REFERENCES deposit_accounts(id),
    transaction_type   VARCHAR(255) NOT NULL,
    amount             NUMERIC NOT NULL,
    balance_after      NUMERIC,
    reference_type     VARCHAR(255) NOT NULL,
    reference_id       BIGINT NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT wallet_tx_transaction_type_check CHECK (transaction_type IN ('CHARGE', 'PAYMENT', 'REFUND')),
    CONSTRAINT wallet_tx_reference_type_check CHECK (reference_type IN ('CHARGE_REQUEST', 'ORDER_PAYMENT')),
    CONSTRAINT uk_wallet_tx_account_ref UNIQUE (deposit_account_id, reference_type, reference_id, transaction_type)
);

-- 3. charge_requests
CREATE TABLE IF NOT EXISTS charge_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL,
    amount          NUMERIC NOT NULL,
    status          VARCHAR(255) NOT NULL,
    pg_provider     VARCHAR(255) NOT NULL,
    pg_order_id     VARCHAR(255) NOT NULL UNIQUE,
    pg_payment_key  VARCHAR(255) UNIQUE,
    pg_method       VARCHAR(255),
    failure_code    VARCHAR(255),
    failure_reason  VARCHAR(255),
    requested_at    TIMESTAMP(6) NOT NULL,
    approved_at     TIMESTAMP(6),
    expires_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT charge_requests_status_check CHECK (status IN ('READY', 'IN_PROGRESS', 'DONE', 'FAILED', 'EXPIRED')),
    CONSTRAINT charge_requests_pg_provider_check CHECK (pg_provider IN ('TOSS'))
);

-- 4. order_payments
CREATE TABLE IF NOT EXISTS order_payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL UNIQUE,
    member_id    BIGINT NOT NULL,
    amount       NUMERIC NOT NULL,
    status       VARCHAR(255) NOT NULL,
    paid_at      TIMESTAMP(6) NOT NULL,
    confirmed_at TIMESTAMP(6),
    refunded_at  TIMESTAMP(6),
    CONSTRAINT order_payments_status_check CHECK (status IN ('PAID', 'CONFIRMED', 'REFUNDED'))
);

-- 5. payment_records (멱등성 키)
CREATE TABLE IF NOT EXISTS payment_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    order_id        BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    amount          NUMERIC NOT NULL,
    status          VARCHAR(255) NOT NULL,
    fail_reason     VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT payment_records_status_check CHECK (status IN ('SUCCESS', 'FAIL'))
);
