-- member-postgres(openbake_member DB)에 적용할 스키마.
-- 기존 공유 DB(openbake)의 members/auths 테이블을 \d로 그대로 떠서 옮긴 것이다.
-- member-service가 Hibernate ddl-auto: update로 만드는 것과 동일한 구조라야 하므로,
-- Member/AuthCredential 엔티티에 컬럼이 추가/변경되면 이 파일도 같이 고쳐야 한다.

CREATE TABLE IF NOT EXISTS members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role         VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    deleted_at   TIMESTAMP(6),
    CONSTRAINT members_role_check CHECK (role IN ('ADMIN', 'CUSTOMER')),
    CONSTRAINT members_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

-- Hibernate가 AuthCredential 엔티티 매핑에서 allocationSize=50을 기대하므로 반드시 INCREMENT BY 50이어야 한다.
CREATE SEQUENCE IF NOT EXISTS auths_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS auths (
    id            BIGINT NOT NULL PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    member_id     BIGINT NOT NULL,
    password_hash VARCHAR(255),
    provider      VARCHAR(255) NOT NULL,
    provider_id   VARCHAR(255),
    CONSTRAINT auths_provider_check CHECK (provider IN ('LOCAL', 'GOOGLE'))
);
